# Generated by Django 5.1.3 on 2024-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packet",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="packet",
            name="dst_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packet",
            name="dst_port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packet",
            name="protocol",
            field=models.CharField(default="UNKNOWN", max_length=10),
        ),
        migrations.AddField(
            model_name="packet",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packet",
            name="src_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packet",
            name="src_port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(
                fields=["-timestamp"], name="monitor_pac_timesta_8a04cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(
                fields=["protocol"], name="monitor_pac_protoco_e9bf78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(fields=["src_ip"], name="monitor_pac_src_ip_2719dc_idx"),
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(fields=["dst_ip"], name="monitor_pac_dst_ip_b3deca_idx"),
        ),
    ]
