# Generated by Django 5.1.3 on 2024-11-20 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_alter_packet_options_packet_dst_ip_packet_dst_port_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("cpu_usage", "CPU Usage"),
                            ("memory_usage", "Memory Usage"),
                            ("disk_usage", "Disk Usage"),
                            ("network_traffic", "Network Traffic"),
                            ("port_scan", "Port Scan Detection"),
                            ("high_traffic_ip", "High Traffic IP"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("email_notification", models.BooleanField(default=False)),
                (
                    "notification_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_value", models.FloatField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "threshold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.alertthreshold",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
